name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - master


jobs:

  build:
  name: merkle_fileserver tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cd merkle_fileserver
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cd merkle_fileserver
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cd merkle_fileserver
          cargo build --release